title: "#pragmathics"
baseurl: /
host: pages.pragmathics.nl
markdown: kramdown
kramdown:
  math_engine: katex

defaults:
- scope:
    path: ""
  values:
    layout: default
    header: true
- scope:
    path: ""
    type: posts
  values:
    header: false
    footer: true
    layout: post