title: "#pragmathics"
baseurl: /
host: pragmathics.nl
url: https://pragmathics.nl
markdown: kramdown
permalink: /:categories/:year/:month/:day/:title/ # Equivalent to permalink: pretty
kramdown:
  math_engine: katex

defaults:
- scope:
    path: ""
  values:
    layout: default
    header: main-header.html
    footer: false
    hide_toc: true
    katex: auto
    lang: en
- scope:
    path: ""
    type: posts
  values:
    header: post-header.html
    footer: post-footer.html
- scope:
    path: ""
    type: klad
  values:
    permalink: /klad/:categories/:title/
    header: post-header.html
    footer: last-processed.html

collections:
  klad:
    output: true