title: "#pragmathics"
baseurl: /
host: pragmathics.nl
markdown: kramdown
kramdown:
  math_engine: katex

defaults:
- scope:
    path: ""
  values:
    layout: default
    header: main-header.html
    footer: false
    katex: auto
- scope:
    path: ""
    type: posts
  values:
    header: post-header.html
    footer: post-footer.html